import Navbar from "../components/Nav";
import { cn } from "../utils/cn";
import "./app.scss";
import { courier, inter } from "./fonts";

export const metadata = {
	title: 'Tony Nguyen',
	description: 'Generated by Next.js',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en" className={inter.className}>
			<body>
				<div className="relative min-h-[100dvh] flex flex-row bg-tony-white">
					<Navbar className="top-0 left-0 bottom-0 h-[100dvh] bg-tony-green fixed w-10/12 md:sticky md:w-1/5 min-w-[350px]" />
					<main className={cn("w-full md:w-4/5 flex flex-col font-medium pt-16 min-h-full", courier.className)} >
						{children}
						<span className="text-xs text-gray-400 my-10 block text-center">Copyright &copy; {new Date().getFullYear()}</span>
					</main>
				</div>
			</body>
		</html>
	)
}
